### ISSUE TITLE
Feature Request: Add visual depth to block representations

### ISSUE THREAD

**Issue by nuc1e4r5n4k3** [OrangeDrangon/Explorer-Angular#10]
See my original for an example. Does not have to be the exact same, but would be nice to have some kind of visual distinction between header, block metadata and transactions.

Especially since transactions are scrollable, and there is only a tiny scrollbar to indicate this.

**Comment by OrangeDrangon** [comment]
Added special color to the header in 95da708c55f57bb4f0161989a6658574dec65b96

If this is not what you wanted or not enough please reopen.
